# Generated by Django 5.0.2 on 2024-02-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color_bnw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_colorized', models.ImageField(upload_to='colored/finished')),
            ],
        ),
    ]
